# Generated by Django 2.2.7 on 2020-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jishusei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jishusei',
            name='edu_background',
        ),
        migrations.AddField(
            model_name='jishusei',
            name='edu_background_duration_m',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jishusei',
            name='edu_background_duration_y',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
