# Generated by Django 2.2.7 on 2019-12-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191211_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='summary_or_promotion',
            field=models.TextField(default=999),
            preserve_default=False,
        ),
    ]
